services:

  edclgpsdb:
    container_name: edclgpsdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EdclGpsDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_edclgpsdb:/var/lib/postgresql/data/