# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "/home/me-ubuntu/Office/Fid/Api/new3/EDCLGPSAPI/src"
      dockerfile: "Bootstrapper/Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "api:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "/home/me-ubuntu/Office/Fid/Api/new3/EDCLGPSAPI/src/Bootstrapper/Api:/app:rw"
    - "/home/me-ubuntu/Office/Fid/Api/new3/EDCLGPSAPI/src:/src:rw"
    - "/home/me-ubuntu/.nuget/packages:/root/.nuget/packages"
    - "/home/me-ubuntu/.local/share/JetBrains/RiderRemoteDebugger/2025.1.2/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/home/me-ubuntu/Tools/Jetbrains/JetBrains Rider-2025.1.2/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/me-ubuntu/.cache/JetBrains/Rider2025.1/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_5_23_10_16_24:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
