# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "/home/me-ubuntu/Office/Fid/Api/EDCLGPSAPI/src"
      dockerfile: "Bootstrapper/Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "api:dev"
    ports: []
    volumes:
    - "/home/me-ubuntu/Office/Fid/Api/EDCLGPSAPI/src/Bootstrapper/Api:/app:rw"
    - "/home/me-ubuntu/Office/Fid/Api/EDCLGPSAPI/src:/src:rw"
    - "/home/me-ubuntu/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
